#!/bin/bash

config_file=$(dirname $(readlink -f $0))/config.sh
test ! -r "$config_file" && config_file=$ASSIGNDIR/../../scripts/config.sh

test -r "$config_file" && . "$config_file"

set -o pipefail
case "$0" in
*dryrun)\
	# FIXME
	base_dir=/web/cs2041/17s2/ 
	export PATH="$base_dir/scripts:/usr/local/bin:/usr/bin:/bin:/sbin:/sbin:/usr/sbin:$PATH"
	export PYTHONPATH="$base_dir/lib/python:$PYTHONPATH"
	export LANG=en_AU.UTF-8  
	export LANGUAGE=en_AU:en  
	export LC_ALL=en_AU.UTF-8  
	export LC_COLLATE=POSIX
	$base_dir/lib/python/cse/autotest.py "$@" 2>&1 | tee "!dryrun_record"
	;;
*)
	if test -n "$autotest_upload_url"
	then
		$public_html_session_directory/lib/python/cse/autotest.py --ssh_upload_url "$autotest_upload_url" "$@"
	else
		$public_html_session_directory/lib/python/cse/autotest.py "$@"
	fi
esac
