#!/usr/bin/env python3.5

import os, re, subprocess, sys
from jinja2 import Environment, FileSystemLoader, select_autoescape

scriptdir = os.path.dirname(os.path.realpath(sys.argv[0]))
basedir = os.path.dirname(scriptdir)
sys.path.append(os.path.join(basedir, 'lib', 'python'))

env = Environment(loader=FileSystemLoader(basedir),
	autoescape=select_autoescape(['html', 'xml']))
for file in sys.argv[1:]:
	with open(file) as template:
		text = template.read()
		try:
			env.parse(text)
		except Exception as e:
			print(file + ':', e)
			sys.exit(1)
	text = re.sub(r'{{.*?}}', '', text)
	if not os.path.exists('/usr/bin/tidy'):
		continue
	p = subprocess.run(['/usr/bin/tidy', '-errors'], input=text, universal_newlines=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
	full_pathname = os.path.join(basedir, file)
	for line in p.stdout.splitlines():
		m =	 re.match(r'^line (\d+) column (\d+) - (.*)', line)
		if not m:
			continue
		(line_number, column, error) = m.groups()
		if re.search(r'DOCTYPE|<body|ul|head>|title|trimming|iframe|summary|"type"|"alt"|missing <li>|escaping malformed URI reference', error):
			continue
		print(':'.join((full_pathname, line_number, column, error)))