#!/bin/bash

unset CDPATH
name="`readlink -f $0`"
base_dir=$(dirname $(dirname $(readlink -f "$0")))


export PATH="$base_dir/scripts:/usr/local/bin:/usr/bin:/bin:/sbin:/sbin:/usr/sbin:$PATH"
export PYTHONPATH="$base_dir/lib/python:$PYTHONPATH"
export LANG=en_AU.UTF-8  
export LANGUAGE=en_AU:en  
export LC_ALL=en_AU.UTF-8  
export LC_COLLATE=POSIX

$base_dir/lib/python/cse/parse_autotest_directory.py "$@"
