#!/bin/sh
unset CDPATH
full_pathname="`readlink -f $0`"
script_dir=`dirname $full_pathname`
dir=`readlink -f $script_dir/..`
cd $dir || exit 1
setsid $script_dir/build >.build_output 2>&1 </dev/null &
