#!/bin/sh

. $(dirname $(readlink -f $0))/config.sh

for arg in "$@" 
do
	for file in $OUT/*/$arg*
	do
		class=$(basename $(dirname "$file"))
		lab=$(basename "$file"|sed 's/\..*//')
		zid=$(basename "$file"|sed 's/.*\.//')
		mark=`egrep -i '^!!specialmark' $file|perl -pe 's?/[^/]*$??;s/.*\s//'`
		echo "$zid|$lab|$mark|"
		echo "$zid|$lab|$mark|" >>$SMSDB/update_recs/$lab.upd
		perl -pi -e 's/^(!!finalmark.*?)___+/${1}'"$mark/" $file
		echo mv $file $MARKED/$class/
		mv $file $MARKED/$class/
	done
done
