#!/bin/bash -p

# postsub only has a EUID of the class account, so ssh to get the uid of the class account
# the ssh depends on the class account having its own private key as an authorized key

# we use a python ssh client because /usr/bin/ssh seems to surrender EUID

#set -x
. $(dirname $(readlink -f $0))/config.sh
$scripts_directory/ssh.py $home_directory/.ssh/id_rsa $course_account@login $scripts_directory/postsub_git1 "$@"
